title: 'lokee''z placeground'
author:
  name: lokee
taxonomies:
  - category
  - tag
  - month
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 5000
  delimiter: '==='
redirects:
  /redirect-test: /
  '/old/(.*)': /new/$1
routes:
  /something/else: /blog/sample-3
  '/new/(.*)': /blog/$1
blog:
  route: ''
